import { canvasEvent, digest, type Tx } from "../../adapters/postgres/database.js";
import { appendMessage, projectToolOutcome } from "../execution/messages.js";
import { result } from "../execution/tool-calls.js";
import { intentBasis, intentCovered, reviewerFor } from "./intents.js";
import { managementChain } from "./policy.js";

export async function finishApproval(
  tx: Tx,
  request: any,
  status: string,
  output = {
    ...result({
      status,
      requestId: request.id,
      executed: false,
      reviewerId: request.assigned_reviewer_id ?? null,
      routeReason: request.route_reason,
      nextAction:
        "The operation was not executed. Inspect this request by requestId; report the blocker and retain saved artifacts. Do not resubmit the same operation through another tool without new authorization.",
    }),
    isError: true,
  },
) {
  await tx.query(
    "update approvals set status=$2,version=version+1,decided_at=now(),result=$3 where id=$1",
    [request.id, status, JSON.stringify(output)],
  );
  await tx.query(
    "update tool_calls set state='failed',result=$2,delivered_at=null,updated_at=now() where id=$1 and state in('waiting','prepared')",
    [request.origin_call_id, JSON.stringify(output)],
  );
  await wakeOrigin(tx, request.origin_call_id);
  await projectToolOutcome(tx, request.origin_call_id);
  await canvasEvent(tx, request.canvas_id, "approval.changed", {
    id: request.id,
    agentId: request.subject_id,
    status,
  });
}
export async function wakeOrigin(tx: Tx, callId: string) {
  await tx.query(
    `update runs set state='queued',reason=null,available_at=now() where id=(select run_id from tool_calls where id=$1)
    and state='waiting' and reason in('approval','message') and cancel_requested_at is null`,
    [callId],
  );
  await tx.query("select pg_notify('intrica_run_wake',run_id) from tool_calls where id=$1", [
    callId,
  ]);
}
export async function notifyReviewer(tx: Tx, request: any) {
  if (!request.assigned_reviewer_id) return;
  const c = (
    await tx.query("select id from conversations where agent_id=$1", [request.assigned_reviewer_id])
  ).rows[0];
  if (!c) return;
  // These fields are generated by the server. Never relay the applicant's reason or tool arguments.
  const active = (
    await tx.query(
      "select id from runs where subject_id=$1 and state in('queued','running','waiting') and cancel_requested_at is null",
      [c.id],
    )
  ).rows[0];
  await appendMessage(
    tx,
    c.id,
    `approval-${request.id}-${request.version}`,
    "permission_notice",
    {
      requestId: request.id,
      text: JSON.stringify({
        event: "permission_review",
        requestId: request.id,
        version: request.version,
        subjectId: request.subject_id,
        kind: request.action.kind,
        role: request.action.role,
        reviewDueAt: request.review_due_at,
      }),
    },
    active?.id,
  );
  await tx.query(
    "update runs set state='queued',reason=null,available_at=now() where subject_id=$1 and state='waiting' and reason in('message','approval') and cancel_requested_at is null",
    [c.id],
  );
  await canvasEvent(tx, request.canvas_id, "conversation.changed", {
    agentId: request.assigned_reviewer_id,
  });
}
export async function escalateApproval(tx: Tx, request: any, reason = "escalated", toUser = false) {
  const reviewer = toUser
    ? null
    : await reviewerFor(
        tx,
        request.subject_id,
        request.action,
        request.assigned_reviewer_id ?? undefined,
      );
  const updated = (
    await tx.query(
      "update approvals set assigned_reviewer_id=$2,review_due_at=case when $2::text is null then null else now()+interval '5 minutes' end,route_reason=$3,version=version+1 where id=$1 returning *",
      [request.id, reviewer, reason],
    )
  ).rows[0];
  await notifyReviewer(tx, updated);
  await canvasEvent(tx, request.canvas_id, "approval.changed", {
    id: request.id,
    agentId: request.subject_id,
    status: "pending",
  });
}
/** Invoked in the same canvas transaction as permission/hierarchy mutations and by maintenance. */
export async function reconcileApprovals(tx: Tx, canvasId: string) {
  const rows = (
    await tx.query(
      "select a.*,t.state as tool_state,r.subject_id as conversation_id,r.state as run_state,r.cancel_requested_at from approvals a left join tool_calls t on t.id=a.origin_call_id left join runs r on r.id=t.run_id where a.canvas_id=$1 and a.status='pending' for update of a",
      [canvasId],
    )
  ).rows;
  for (const r of rows) {
    if (
      !r.run_state ||
      r.cancel_requested_at ||
      ["cancelled", "failed", "succeeded"].includes(r.run_state)
    ) {
      await finishApproval(tx, r, "cancelled");
      continue;
    }
    if (new Date(r.expires_at).getTime() <= Date.now()) {
      await finishApproval(tx, r, "expired");
      continue;
    }
    let basis: Record<string, unknown>;
    try {
      basis = await intentBasis(tx, r.subject_id, r.action);
    } catch {
      await finishApproval(tx, r, "invalidated");
      continue;
    }
    const sticky =
      !r.assigned_reviewer_id &&
      ["escalated", "manager_timeout", "manager_unavailable"].includes(r.route_reason);
    const sameTarget =
      digest({ ...basis, role: undefined, delta: undefined, grant: undefined }) ===
      digest({ ...r.basis, role: undefined, delta: undefined, grant: undefined });
    const unknown = (
      await tx.query(
        "select 1 from tool_calls t join runs r on r.id=t.run_id where r.subject_id=$1 and t.state='unknown' limit 1",
        [r.conversation_id],
      )
    ).rowCount;
    const authority =
      !sticky && !unknown && sameTarget && ["prepared", "waiting"].includes(r.tool_state)
        ? await intentCovered(tx, r.subject_id, r.action)
        : null;
    if (authority) {
      const output = result({ status: "satisfied", requestId: r.id, executed: false, authority });
      await tx.query(
        "update approvals set status='satisfied',version=version+1,decided_by=null,decided_at=now(),execution_basis=$2,result=$3 where id=$1",
        [r.id, JSON.stringify(basis), JSON.stringify(output)],
      );
      await tx.query(
        "update tool_calls set state=$2,result=$3,delivered_at=null,updated_at=now() where id=$1 and state in('waiting','prepared')",
        [
          r.origin_call_id,
          r.complete_tool ? "succeeded" : "prepared",
          r.complete_tool ? JSON.stringify(output) : null,
        ],
      );
      await wakeOrigin(tx, r.origin_call_id);
      await projectToolOutcome(tx, r.origin_call_id);
      await canvasEvent(tx, r.canvas_id, "approval.changed", {
        id: r.id,
        agentId: r.subject_id,
        status: "satisfied",
      });
      continue;
    }
    if (digest(basis) !== digest(r.basis)) {
      await finishApproval(tx, r, "invalidated");
      continue;
    }
    const timedOut = r.review_due_at && new Date(r.review_due_at).getTime() <= Date.now();
    if (timedOut) {
      await escalateApproval(tx, r, "manager_timeout");
      continue;
    }
    const chain = await managementChain(tx, r.subject_id);
    const reviewer = sticky
      ? null
      : r.assigned_reviewer_id && chain.includes(r.assigned_reviewer_id)
        ? r.assigned_reviewer_id
        : await reviewerFor(tx, r.subject_id, r.action);
    if (reviewer !== r.assigned_reviewer_id) {
      const updated = (
        await tx.query(
          `update approvals set assigned_reviewer_id=$2,route_reason=$3,review_due_at=case when $2::text is null then null else now()+interval '5 minutes' end,version=version+1 where id=$1 returning *`,
          [r.id, reviewer, timedOut ? "manager_timeout" : reviewer ? "manager" : "user"],
        )
      ).rows[0];
      await notifyReviewer(tx, updated);
      await canvasEvent(tx, canvasId, "approval.changed", {
        id: r.id,
        agentId: r.subject_id,
        status: "pending",
      });
    }
  }
}
