import type { Node } from "@intrica/contracts";
import { nodeDisplayTitle } from "./graph";

// Keep the index small and local. These are the characters most often used in canvas labels;
// Latin titles continue to use the normal case-insensitive search path.
const PINYIN: Record<string, string> = Object.fromEntries([
  ["资", "zi"],
  ["料", "liao"],
  ["甲", "jia"],
  ["乙", "yi"],
  ["丙", "bing"],
  ["画", "hua"],
  ["布", "bu"],
  ["节", "jie"],
  ["点", "dian"],
  ["图", "tu"],
  ["片", "pian"],
  ["网", "wang"],
  ["页", "ye"],
  ["文", "wen"],
  ["件", "jian"],
  ["夹", "jia"],
  ["目", "mu"],
  ["录", "lu"],
  ["容", "rong"],
  ["器", "qi"],
  ["待", "dai"],
  ["办", "ban"],
  ["事", "shi"],
  ["项", "xiang"],
  ["代", "dai"],
  ["理", "li"],
  ["模", "mo"],
  ["型", "xing"],
  ["思", "si"],
  ["考", "kao"],
  ["回", "hui"],
  ["复", "fu"],
  ["提", "ti"],
  ["示", "shi"],
  ["词", "ci"],
  ["研", "yan"],
  ["究", "jiu"],
  ["报", "bao"],
  ["告", "gao"],
  ["设", "she"],
  ["计", "ji"],
  ["开", "kai"],
  ["发", "fa"],
  ["测", "ce"],
  ["试", "shi"],
  ["产", "chan"],
  ["品", "pin"],
  ["用", "yong"],
  ["户", "hu"],
  ["需", "xu"],
  ["求", "qiu"],
  ["数", "shu"],
  ["据", "ju"],
  ["分", "fen"],
  ["析", "xi"],
  ["会", "hui"],
  ["话", "hua"],
  ["历", "li"],
  ["史", "shi"],
  ["协", "xie"],
  ["作", "zuo"],
  ["任", "ren"],
  ["务", "wu"],
  ["状", "zhuang"],
  ["态", "tai"],
  ["新", "xin"],
  ["旧", "jiu"],
  ["上", "shang"],
  ["下", "xia"],
  ["中", "zhong"],
  ["心", "xin"],
  ["左", "zuo"],
  ["右", "you"],
  ["前", "qian"],
  ["后", "hou"],
  ["大", "da"],
  ["小", "xiao"],
  ["总", "zong"],
  ["结", "jie"],
  ["论", "lun"],
  ["方", "fang"],
  ["案", "an"],
  ["原", "yuan"],
  ["因", "yin"],
  ["结", "jie"],
  ["果", "guo"],
  ["注", "zhu"],
  ["意", "yi"],
  ["事", "shi"],
  ["情", "qing"],
  ["人", "ren"],
  ["员", "yuan"],
  ["团", "tuan"],
  ["队", "dui"],
  ["管", "guan"],
  ["理", "li"],
  ["员", "yuan"],
  ["权", "quan"],
  ["限", "xian"],
  ["本", "ben"],
  ["地", "di"],
  ["方", "fang"],
  ["路", "lu"],
  ["径", "jing"],
  ["源", "yuan"],
  ["案", "an"],
  ["例", "li"],
  ["主", "zhu"],
  ["题", "ti"],
  ["阅", "yue"],
  ["读", "du"],
  ["编", "bian"],
  ["辑", "ji"],
  ["代", "dai"],
  ["码", "ma"],
]);

export function mentionSearchKeys(node: Node) {
  const title = nodeDisplayTitle(node).trim().toLocaleLowerCase();
  const pinyin = [...title].map((char) => PINYIN[char] ?? char).join("");
  const initials = [...title].map((char) => PINYIN[char]?.[0] ?? char).join("");
  return { title, pinyin, initials, kind: node.kind };
}

export function matchesMention(node: Node, query: string) {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return true;
  const keys = mentionSearchKeys(node);
  return [keys.title, keys.pinyin, keys.initials, keys.kind].some((key) =>
    key.includes(normalized),
  );
}
